# Generated by Django 6.0.6 on 2026-07-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_slider_description_remove_slider_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional: Photo of the person', null=True, upload_to='testimonials/'),
        ),
    ]
