# Generated by Django 6.0.6 on 2026-07-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_testimonial_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Active Members, Events Organized', max_length=100)),
                ('count', models.IntegerField(default=0, help_text='Target number to count up to')),
                ('icon_class', models.CharField(default='bi-people-fill', help_text='Bootstrap Icon class, e.g. bi-people-fill, bi-calendar-check-fill', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
