# Generated by Django 6.0.6 on 2026-07-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', models.TextField(default='To build a fearless and empowered community of journalists where truth prevails, and every voice is heard and protected across the nation.', help_text='Enter the Vision statement for the home page.')),
                ('mission', models.TextField(default='We are dedicated to safeguarding the rights of the press, providing essential support to media professionals, and promoting ethical, unbiased journalism for a stronger democracy.', help_text='Enter the Mission statement for the home page.')),
            ],
            options={
                'verbose_name': 'Vision & Mission',
                'verbose_name_plural': 'Vision & Mission',
            },
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
