# Generated by Django 6.0.6 on 2026-07-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
