# Generated by Django 6.0.6 on 2026-07-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_certificate_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
