# Generated by Django 6.0.6 on 2026-07-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_event_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visionmission',
            options={'verbose_name': 'Mission', 'verbose_name_plural': 'Mission'},
        ),
        migrations.RemoveField(
            model_name='visionmission',
            name='vision',
        ),
        migrations.AddField(
            model_name='visionmission',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for the mission section.', null=True, upload_to='mission/'),
        ),
        migrations.AlterField(
            model_name='visionmission',
            name='mission',
            field=models.TextField(default='We are dedicated to safeguarding the rights of the press, providing essential support to media professionals, and promoting ethical, unbiased journalism for a stronger democracy.', help_text='Enter the Mission statement.'),
        ),
    ]
